version: "3.8"
services:
  backend:
    build:
      context: ./python-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      # recommended: set IBM_QUANTUM_TOKEN in host environment before 'docker-compose up'
      - IBM_QUANTUM_TOKEN=${IBM_QUANTUM_TOKEN}
      - IBM_RUNTIME_CHANNEL=${IBM_RUNTIME_CHANNEL}
    volumes:
      - ./python-backend:/app
  # frontend service is optional; if you have a Next.js frontend in ./frontend, uncomment and use it.
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      # frontend must call the backend container name (backend) when using docker-compose network
      - NEXT_PUBLIC_API_URL=http://backend:5000
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend